/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

/**
 *
 * @author khangnlbk
 */
public class CardInformation extends javax.swing.JFrame {

    /**
     * Creates new form CardInformation
     */
    public CardInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cardNumberLabel = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        expiredDateLabel = new javax.swing.JLabel();
        studentIDLabel = new javax.swing.JLabel();
        studyPeriodLabel = new javax.swing.JLabel();
        fullNameEditBt = new javax.swing.JButton();
        emailEditBt = new javax.swing.JButton();
        genderEditBt = new javax.swing.JButton();
        contactEditBt = new javax.swing.JButton();
        expiredDateEditBt = new javax.swing.JButton();
        studentIDEditBt = new javax.swing.JButton();
        studyPeriodEditBt = new javax.swing.JButton();
        updateCardbt = new javax.swing.JButton();
        cancelUpdateCardBt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        topMenu = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        card = new javax.swing.JMenu();
        book = new javax.swing.JMenu();
        logOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Card number");

        jLabel2.setText("User name");

        jLabel3.setText("Full name");

        jLabel4.setText("Email");

        jLabel5.setText("Gender");

        jLabel6.setText("Contact");

        jLabel7.setText("Expired Date");

        jLabel8.setText("Student ID");

        jLabel9.setText("Studey Period");

        fullNameEditBt.setText("Edit");

        emailEditBt.setText("Edit");

        genderEditBt.setText("Edit");

        contactEditBt.setText("Edit");

        expiredDateEditBt.setText("Edit");

        studentIDEditBt.setText("Edit");

        studyPeriodEditBt.setText("Edit");

        updateCardbt.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        updateCardbt.setText("Update");

        cancelUpdateCardBt.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cancelUpdateCardBt.setText("Cancel");

        jLabel10.setText("Hedspi Library");

        jLabel11.setText("Libarian");

        home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jframe/image/homeicon.png"))); // NOI18N
        home.setText("Home");
        topMenu.add(home);

        card.setBackground(new java.awt.Color(39, 75, 77));
        card.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jframe/image/cardicon.png"))); // NOI18N
        card.setText("Card");
        topMenu.add(card);

        book.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jframe/image/bookicon.png"))); // NOI18N
        book.setText("Book");
        topMenu.add(book);

        logOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jframe/image/logouticon.jpg.png"))); // NOI18N
        logOut.setText("Log out");
        topMenu.add(logOut);

        setJMenuBar(topMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userNameLabel)
                            .addComponent(cardNumberLabel)
                            .addComponent(fullNameLabel)
                            .addComponent(emailLabel)
                            .addComponent(genderLabel)
                            .addComponent(contactLabel)
                            .addComponent(expiredDateLabel)
                            .addComponent(studentIDLabel)
                            .addComponent(studyPeriodLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullNameEditBt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailEditBt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genderEditBt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contactEditBt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(expiredDateEditBt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentIDEditBt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studyPeriodEditBt, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(updateCardbt)
                                .addGap(57, 57, 57)
                                .addComponent(cancelUpdateCardBt))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)
                                        .addGap(20, 20, 20)))))
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cardNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fullNameLabel)
                    .addComponent(fullNameEditBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emailLabel)
                    .addComponent(emailEditBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(genderLabel)
                    .addComponent(genderEditBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(contactLabel)
                    .addComponent(contactEditBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(expiredDateLabel)
                    .addComponent(expiredDateEditBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(studentIDLabel)
                    .addComponent(studentIDEditBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(studyPeriodLabel)
                    .addComponent(studyPeriodEditBt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCardbt)
                    .addComponent(cancelUpdateCardBt))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu book;
    private javax.swing.JButton cancelUpdateCardBt;
    private javax.swing.JMenu card;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JButton contactEditBt;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JButton emailEditBt;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton expiredDateEditBt;
    private javax.swing.JLabel expiredDateLabel;
    private javax.swing.JButton fullNameEditBt;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JButton genderEditBt;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JMenu home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu logOut;
    private javax.swing.JButton studentIDEditBt;
    private javax.swing.JLabel studentIDLabel;
    private javax.swing.JButton studyPeriodEditBt;
    private javax.swing.JLabel studyPeriodLabel;
    private javax.swing.JMenuBar topMenu;
    private javax.swing.JButton updateCardbt;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
